name: mico_learn
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.9.2
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.3+1
  equatable: ^2.0.5
  firebase_core: ^2.25.4
  flutter_bloc: ^8.1.5
  flutter_easyloading: ^3.0.5
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.5
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  get_it: ^7.6.8
  google_sign_in: ^6.2.1
  injectable: ^2.4.1
  intl: ^0.19.0
  loading_animation_widget: ^1.2.1
  logger: ^2.2.0
  lottie: ^3.1.0
  percent_indicator: ^4.2.3
  responsive_framework: ^1.4.0
  rive: ^0.13.4
  supabase_flutter: ^2.5.0
  video_player: ^2.8.6
  webview_flutter: ^4.7.0

  
dependency_overrides:
  meta: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^7.3.2
  build_runner: ^2.4.9
  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.6

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/illustrations/
    - assets/images/icons/
    - assets/images/logo/
    - assets/lottie/
    - assets/rive/
     
  fonts:
    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Text-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Text-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600