// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2D3-LxTvRKSuGIRPJOfT5v_6F0QN247Q',
    appId: '1:1014456511008:web:92fb81b574b1a0a081ea45',
    messagingSenderId: '1014456511008',
    projectId: 'micolearn',
    authDomain: 'micolearn.firebaseapp.com',
    storageBucket: 'micolearn.appspot.com',
    measurementId: 'G-H273BK6EZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoAE3yY1ll6GY_0U2zPiTWEh3S-cYVv9E',
    appId: '1:1014456511008:android:66cea81e37934ab181ea45',
    messagingSenderId: '1014456511008',
    projectId: 'micolearn',
    storageBucket: 'micolearn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI12vdY77smeuyCu_KebP4D_fWRFf30QM',
    appId: '1:1014456511008:ios:a4e4c52298b63f8681ea45',
    messagingSenderId: '1014456511008',
    projectId: 'micolearn',
    storageBucket: 'micolearn.appspot.com',
    iosBundleId: 'com.mvzd.micoLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI12vdY77smeuyCu_KebP4D_fWRFf30QM',
    appId: '1:1014456511008:ios:a4e4c52298b63f8681ea45',
    messagingSenderId: '1014456511008',
    projectId: 'micolearn',
    storageBucket: 'micolearn.appspot.com',
    iosBundleId: 'com.mvzd.micoLearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2D3-LxTvRKSuGIRPJOfT5v_6F0QN247Q',
    appId: '1:1014456511008:web:cf3e4708de6abb8981ea45',
    messagingSenderId: '1014456511008',
    projectId: 'micolearn',
    authDomain: 'micolearn.firebaseapp.com',
    storageBucket: 'micolearn.appspot.com',
    measurementId: 'G-CEHB94SWQ7',
  );
}
